version: '3'
services:

    web:
        build:
            context: ../nginx/
            dockerfile: docker/Dockerfile
        image: "laravel-nginx:latest"
        ports:
            - "${APP_PORT:-80}:80"
        volumes:
            - ../nginx:/usr/share/nginx/html


    app:
        build:
            context: ../laravel/
            dockerfile: docker/Dockerfile
        image: "laravel-php:latest"
        environment:
            ## Application Configuration ##
            APP_ENV: "dev"
            APP_DEBUG: "true"
        volumes:
            - ../laravel:/var/www/html


    mariadb:
        build:
            context: ../mariadb/
            dockerfile: docker/Dockerfile
        image: "laravel-mariadb:latest"
        ports:
            - "3306:3306"
        volumes:
            - laravel_dbdata:/var/lib/mysql

    redis:
        build:
            context: ../redis/
            dockerfile: docker/Dockerfile
        image: "laravel-redis:latest"          
        ports:
            - "6379:6379"  


volumes:
    laravel_dbdata:
